config/routes.rb
Rails.application.routes.draw do
  resources :forms
  resources :naveens
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/form.rb
class Form < ApplicationRecord
end

app/models/naveen.rb
class Naveen < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/forms_controller.rb
class FormsController < ApplicationController
  before_action :set_form, only: %i[ show edit update destroy ]

  # GET /forms or /forms.json
  def index
    @forms = Form.all
  end

  # GET /forms/1 or /forms/1.json
  def show
  end

  # GET /forms/new

  
 
  def new
    @form = Form.new
  end

  # GET /forms/1/edit
  def edit
  end

  # POST /forms or /forms.json
  def create
    @form = Form.new(form_params)
   
    respond_to do |format|
      if @form.save
        format.html { redirect_to @form, notice: "Form was successfully created." }
        format.json { render :show, status: :created, location: @form }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @form.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /forms/1 or /forms/1.json

 
  def update
    binding.pry
    respond_to do |format|
      if @form.update(form_params)
        format.html { redirect_to @form, notice: "Form was successfully updated." }
        format.json { render :show, status: :ok, location: @form }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @form.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /forms/1 or /forms/1.json

 
  def destroy
    @form.destroy
    respond_to do |format|
      format.html { redirect_to forms_url, notice: "Form was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_form
      @form = Form.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def form_params
      params.require(:form).permit(:name, :phone)
    end
end

app/controllers/naveens_controller.rb
class NaveensController < ApplicationController
  before_action :set_naveen, only: %i[ show edit update destroy ]

  # GET /naveens or /naveens.json
  def index
    @naveens = Naveen.all
  end

  # GET /naveens/1 or /naveens/1.json
  def show
  end

  # GET /naveens/new
  def new
    @naveen = Naveen.new
  end

 

 

  # GET /naveens/1/edit
  def edit
  end

  # POST /naveens or /naveens.json
  def create
    @naveen = Naveen.new(naveen_params)

    respond_to do |format|
      if @naveen.save
        format.html { redirect_to @naveen, notice: "Naveen was successfully created." }
        format.json { render :show, status: :created, location: @naveen }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @naveen.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /naveens/1 or /naveens/1.json
  def update
    respond_to do |format|
      if @naveen.update(naveen_params)
        format.html { redirect_to @naveen, notice: "Naveen was successfully updated." }
        format.json { render :show, status: :ok, location: @naveen }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @naveen.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /naveens/1 or /naveens/1.json
  def destroy
    @naveen.destroy
    respond_to do |format|
      format.html { redirect_to naveens_url, notice: "Naveen was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_naveen
      @naveen = Naveen.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def naveen_params
      params.require(:naveen).permit(:name1,:phone)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/forms_helper.rb
module FormsHelper
end

app/helpers/naveens_helper.rb
module NaveensHelper
end

app/views/forms/_form.html.erb
<%= form_with(model: form) do |form| %>
  <% if @form.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@form.errors.count, "error") %> prohibited this form from being saved:</h2>

      <ul>
        <% form.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field" >
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :phone %>
    <%= form.text_field :phone %>
  </div>
  
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/forms/edit.html.erb
<h1>Editing Form</h1>

<%= render 'form', form: @form %>

<%= link_to 'Show', @form %> |
<%= link_to 'Back', forms_path %>

app/views/forms/index.html.erb
<p id="notice"><%= notice %></p>
<br>
<br>

<center>

<h1>welcome to this site</h1></center>

<table>
  <thead>
    
  </thead>
  <center>
  <br>
  <br>
  <%= link_to 'New Form', new_form_path %>

  <br>
  <br>
  <br>
  </center>

  <tbody>
    <% @forms.each do |form| %>
      <tr>
       
        
       

      
        <td><%= link_to 'Show', form %></td>
        <td><%= link_to 'Edit', edit_form_path(form) %></td>
        <td><%= link_to 'Destroy', form, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/forms/new.html.erb
<h1>New Form</h1>

<%= render 'form', form: @form %>

<%= link_to 'Back', forms_path %>

app/views/forms/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @form.name %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @form.phone %>
</p>





<%= link_to 'Edit', edit_form_path(@form) %> |
<%= link_to 'Back', forms_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Name</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/naveens/_form.html.erb
<%= form_with(model: naveen) do |form| %>
  <% if @naveen.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(naveen.errors.count, "error") %> prohibited this naveen from being saved:</h2>

      <ul>
        <% naveen.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class ="field">
    <%= form.label :name1 %>
    <%= form.text_field :name1 %>
  </div>
  <div class="field">
  <%= form.label :phone %>
  <%= form.text_field :phone%>
  </div>

 

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/naveens/edit.html.erb
<h1>Editing Naveen</h1>

<%= render 'form', naveen: @naveen %>

<%= link_to 'Show', @naveen %> |
<%= link_to 'Back', naveens_path %>

app/views/naveens/index.html.erb
<p id="notice"><%= notice %></p>

<h1>THE NAME IS </h1>

<table>
  <thead>
    <tr>
      <th>Name1</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <body>
    <% @naveens.each do |naveen| %>
      <tr>
        <td><%= naveen.name1 %></td>

        <td><%= naveen.phone%></td>
        
        <td><%= link_to 'Show', naveen %></td>
        <td><%= link_to 'Edit', edit_naveen_path(naveen) %></td>
        <td><%= link_to 'Destroy', naveen, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </body>
</table>

<br>

<%= link_to 'New Naveen', new_naveen_path %>

app/views/naveens/new.html.erb
<h1>New Naveen</h1>

<%= render 'form', naveen: @naveen %>

<%= link_to 'Back', naveens_path %>

app/views/naveens/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name1:</strong>
  
  <%= @naveen.name1 %>

  </p>
  <p>

  <strong>Phone:</strong>
  <%= @naveen.phone %>

  </p>

 



<%= link_to 'Edit', edit_naveen_path(@naveen) %> |
<%= link_to 'Back', naveens_path %>